### ISSUE TITLE
API 추가

### ISSUE THREAD

**Issue by roseline124** [angelhack-study-buddies/study-buddies-server#14]
1. User @roseline124 
- [x] N days challenge (연속학습 일수 조회) -> user의 post CreatedAt으로 계산
- [x] recommendations (user가 올렸던 최근 hashTag의 다른 학습자 게시물들 추천)
🧚‍♀️ Post data 추가하고 확인해봐야 함

2. Post @chloe-codes1 
- [x] create
- [x] update
- [x] delete
- [x] read
  - [x] postList 
    - [x] group by: hashtag, author
    - [x] order by: likeCount, createdAt
    - [x] filter by: hashtag name, author id 
- [x] title, content, previewImage @roseline124 + 캐싱

3. LikePost @roseline124 
- [x] LikePost DB 설계 @chloe-codes1 
- [x] postUpdate (isLiked toggle) + LikePostcreate (orDelete)

4. Follower ('^')
- [x] follower db, query

4. API 한 번씩 다 돌려보고 수정
- [x] user
- [x] post crud 
  - [x] create
  - [x] read
  - [x] update
  - [x] delete
- [x] likepost
- [x] hashtag
- [x] follower

**Comment by roseline124** [comment]
User하고 있을게요

**Comment by chloe-codes1** [comment]
넵 Post 하고있습니다! 헤매고 있어요...

**Comment by roseline124** [comment]
> 넵 Post 하고있습니다! 헤매고 있어요...

도와드릴 게 있을까요?

**Comment by chloe-codes1** [comment]
> > 넵 Post 하고있습니다! 헤매고 있어요...
> 
> 도와드릴 게 있을까요?

한 번 봐주실 수 있나요...! Draft로 올려보겠습니닷!
